version: '3.7'
services:
  glpi:
    container_name: glpi-chatbot-app-dev
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
    image: diouxx/glpi
    hostname: glpi.localhost.com
    networks:
      - glpi-chatbotNetwork
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - glpi-app-data:/var/www/html/glpi
  typebot-builder:
    image: baptistearno/typebot-builder:latest
    restart: always
    depends_on:
      - typebot-db
    ports:
      - '8080:3000'
    networks:
      - glpi-chatbotNetwork
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file: ./typebot/.env

  typebot-viewer:
    image: baptistearno/typebot-viewer:latest
    restart: always
    networks:
      - glpi-chatbotNetwork
    ports:
      - '8081:3000'
    env_file: ./typebot/.env

  typebot-db:
    image: postgres:14-alpine
    restart: always
    networks:
      - glpi-chatbotNetwork
    volumes:
      - glpi-typebot-pgData:/var/lib/postgresql/data
    environment:
      - TYPEBOT
      - POSTGRES_DB=typebot
      - POSTGRES_PASSWORD=typebot

  db:
    command: --default-authentication-plugin=mysql_native_password
    container_name: glpi-chatbot-dev-db
    environment:
      MYSQL_DATABASE: glpi-chatbot
      MYSQL_PASSWORD: glpi-chatbot
      MYSQL_ROOT_PASSWORD: glpi-chatbot
      MYSQL_USER: glpi-chatbot
      SERVICE_NAME: mysql
      SERVICE_TAGS: dev
    image: mysql:8.0
    networks:
      - glpi-chatbotNetwork
    ports:
      - 33306:3306
    restart: unless-stopped
    tty: true
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
      - glpi-chatbotMysqlData:/var/lib/mysql

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - mailpit-data:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

networks:
  glpi-chatbotNetwork:
    driver: bridge
volumes:
  glpi-app-data:
  mailpit-data:
  glpi-typebot-pgData:
  glpi-chatbotMysqlData:
    driver: local
    name: glpi-chatbotMysqlData
